services:
  keycloak:
    container_name: 'keycloak'
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 123
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-config.json
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./realm-config.json:/opt/keycloak/data/import/realm-config.json
    command: ["start-dev", "--import-realm"]
  accommodation_app:
    build: .
    container_name: 'accommodation_app'
    ports:
      - '8080:8080'
    depends_on:
      - accommodation_postgres
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://accommodation_postgres:5432/accommodationdb'
      - 'SPRING_DATASOURCE_USERNAME=admin'
      - 'SPRING_DATASOURCE_PASSWORD=admin'
    networks:
      - internal
  accommodation_postgres:
    container_name: 'accommodation_db'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=accommodationdb'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    volumes:
      - 'pgdata:/var/lib/postgresql'
    networks:
      - internal
volumes:
  pgdata:
  keycloak_data:

networks:
  internal:
    driver: bridge
